name: Build Skin Generator

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install dependencies with vcpkg
        run: |
          .\vcpkg\vcpkg.exe install boost-log zlib libzip

      - name: List Boost.Log config file
        run: |
          dir .\vcpkg\installed\x64-windows\share\boost-log

      - name: Configure CMake
        run: |
          cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=.\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_PREFIX_PATH=.\vcpkg\installed\x64-windows .
        
      - name: Build
        run: |
          cmake --build . --config Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: skins_generator_bin
          path: ./bin/*
