name: Build Skin Generator

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install dependencies with vcpkg
        run: |
          .\vcpkg\vcpkg.exe install boost-log zlib

      - name: Build libzip from source
        run: |
          curl -LO https://libzip.org/download/libzip-1.10.1.tar.gz
          tar -xzf libzip-1.10.1.tar.gz
          cd libzip-1.10.1
          cmake -G "Visual Studio 17 2022" ^
            -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake ^
            -DCMAKE_INSTALL_PREFIX=../libzip_install .
          cmake --build . --config Release
          cmake --install . --config Release
          cd ..

      - name: Configure CMake
        run: |
          cmake -G "Visual Studio 17 2022" ^
            -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake .

      - name: Build
        run: |
          cmake --build . --config Release
