name: Build Skin Generator

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config

          # Install zlib
          sudo apt-get install -y zlib1g-dev

          # Install Boost
          sudo apt-get install -y libboost-all-dev

          # Install libzip from source
          wget https://libzip.org/download/libzip-1.10.1.tar.gz
          tar -xzf libzip-1.10.1.tar.gz
          cd libzip-1.10.1
          cmake .
          make
          sudo make install
          cd ..

      - name: Configure
        run: cmake .

      - name: Build
        run: cmake --build .
